version: "3"
services:
  rsem:
    image: biocontainers/rsem
    container_name: rsem
    tty: true
    volumes:
      - ${DIR}:/tmp/wk
    working_dir: /tmp/wk
    command: >
      bash -c "rsem-calculate-expression --alignments --no-bam-output -p ${THREADS} output/${ID}/${ID}_trim.Aligned.toTranscriptome.out.bam ./STARidx/RSEM ${ID} &&
        mv ${ID}* output/${ID}/ "
        
 

          
      
