version: "3"
services:
  star:
    image: quay.io/biocontainers/star:${VER_3}
    container_name: star
    tty: true
    volumes:
      - ${DIR}:/tmp/wk
    working_dir: /tmp/wk
    user: '1001:1001'
    command: >
      STAR --runThreadN ${THREADS} \
           --runMode genomeGenerate \
           --genomeDir ./refs/index/STAR_mRNAlncRNA \
           --genomeFastaFiles ./refs/mRNA.lncRNA.fa \
           --genomeSAindexNbases 12 \
