version: "3"
services:
  parallel-fastq:
    image: quay.io/biocontainers/parallel-fastq-dump:${VER_1}
    container_name: parallel-fastq
    tty: true
    volumes:
      - ${DIR}:/tmp/wk
    working_dir: /tmp/wk
    user: "${UID}:${UID}"
    command: >
      bash -c "parallel-fastq-dump --sra-id ./input/${ID}/${ID}.sra --threads ${THREADS} --gzip && 
      mkdir -p output/${ID} && 
      mv *.fastq.gz output/${ID}/"
