version: "3"
services:
  sra-toolkit:
    image: ncbi/sra-tools:3.0.1
    container_name: sra-prefetch
    tty: true
    volumes:
      - ${DIR}:/tmp/wk
    working_dir: /tmp/wk
    user: '1001:1001'
    command: prefetch ${ID} -O ./input/

