#env in .env file
version: "3"
services:
  sra-toolkit:
    image: ncbi/sra-tools:3.0.1
    container_name: sra-prefetch
    tty: true
    volumes:
      - ${DIR}:/tmp/wk
    working_dir: /tmp/wk
    command: prefetch ${ID} -O ./input/
  
  parallel-fastq:
    image: quay.io/biocontainers/parallel-fastq-dump:${VER_1}
    container_name: parallel-fastq
    tty: true
    volumes:
      - ${DIR}:/tmp/wk
    working_dir: /tmp/wk
    command: >
      bash -c "sh wait-for-it.sh input/${ID}/${ID}.sra parallel-fastq-dump --sra-id ./input/${ID}/${ID}.sra --threads ${THREADS} --gzip &&
      mkdir -p output/${ID} &&
      mv *.fastq.gz output/${ID}/"

  fastp:
    image: quay.io/biocontainers/fastp:${VER_2}
    container_name: fastp
    tty: true
    volumes:
      - ${DIR}:/tmp/wk
    working_dir: /tmp/wk
    command: sh wait-for-it.sh output/${ID}/${ID}.fastq.gz fastp -w 16 -h output/${ID}/${ID}.html -j output/${ID}/${ID}.json -i output/${ID}/${ID}.fastq.gz  -o output/${ID}/${ID}_trim.fastq.gz 

  star:
    image: quay.io/biocontainers/star:${VER_3}
    container_name: star
    tty: true
    volumes:
      - ${DIR}:/tmp/wk
    working_dir: /tmp/wk
    command: >
      sh wait-for-it.sh output/${ID}/${ID}.html  STAR  --runThreadN ${THREADS} \
           --genomeDir STARidx \
           --readFilesIn output/${ID}/${ID}_trim.fastq.gz \
           --readFilesCommand gunzip -c \
           --quantMode TranscriptomeSAM \
           --genomeLoad NoSharedMemory \
           --outSAMtype BAM SortedByCoordinate \
           --outFileNamePrefix output/${ID}/${ID}_trim. \
           --outFilterMultimapNmax 1
  
  rsem:
    image: biocontainers/rsem
    container_name: rsem
    tty: true
    volumes:
      - ${DIR}:/tmp/wk
    working_dir: /tmp/wk
    command: >
      bash -c "sh wait-for-it.sh output/${ID}/${ID}_trim.Log.final.out rsem-calculate-expression --alignments --no-bam-output -p ${THREADS} output/${ID}/${ID}_trim.Aligned.toTranscriptome.out.bam ./STARidx/RSEM ${ID} &&
        mv ${ID}* output/${ID}/"
