version: "3"
services:
  rsem:
    image: biocontainers/rsem
    container_name: rsem
    tty: true
    volumes:
      - ${DIR}:/tmp/wk
    working_dir: /tmp/wk
    user: "1001:1001"
    command: >
      bash -c "rsem-calculate-expression --alignments --no-bam-output -p ${THREADS} ./output/${ID}/${ID}_mapped_mod.sam ./refs/index/mRNA.lncRNA ${ID} &&
        mv ${ID}* output/${ID}/ "
